package Views;

import java.awt.event.ActionListener;
import java.io.File;

public class ImportAssetsView extends javax.swing.JPanel {

    public ImportAssetsView() {
        initComponents();
    }
    
    public boolean getTasksCheckbox() {
        return this.createTasksCheckBox.isSelected();
    }
    
    public File[] getFiles() {
        return this.assetsFileChooser.getSelectedFiles();
    }
    
    public void addFileChooserActionListener(ActionListener listener) {
        this.assetsFileChooser.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assetsFileChooser = new javax.swing.JFileChooser();
        createTasksCheckBox = new javax.swing.JCheckBox();

        assetsFileChooser.setMultiSelectionEnabled(true);

        createTasksCheckBox.setText("Create Inbound QA Tasks for Imported Assets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assetsFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createTasksCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createTasksCheckBox)
                .addGap(11, 11, 11)
                .addComponent(assetsFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser assetsFileChooser;
    private javax.swing.JCheckBox createTasksCheckBox;
    // End of variables declaration//GEN-END:variables
}
