/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Exceptions.NoModelSelectedException;
import Models.Model;
import java.awt.event.ActionListener;
import java.util.Vector;

/**
 *
 * @author ryantk
 */
public class ModelChoiceView extends javax.swing.JFrame {
    
    Vector<Model> availableModels = new Vector<>();
    Vector<Model> chosenModels = new Vector<>();

    /**
     * Creates new form TeamDetailView
     */
    public ModelChoiceView() {
        initComponents();
    }
    
    public Model getSelectedAvailableModel() throws NoModelSelectedException {
        int selectedIndex = listbox_availableModels.getSelectedIndex();
        
        if (selectedIndex < 0)
            throw new NoModelSelectedException();
        
        return availableModels.get(selectedIndex);
    }
    
    public Model getSelectedChosenModel() throws NoModelSelectedException {
        int selectedIndex = listbox_chosenModels.getSelectedIndex();
        
        if (selectedIndex < 0)
            throw new NoModelSelectedException();
        
        return chosenModels.get(selectedIndex);
    }
    
    public Vector<Model> getChosenModels(){
        return (Vector<Model>) chosenModels.clone();
    }
    
    public Vector<Model> getAvailableModels() {
        return (Vector<Model>) availableModels.clone();
    }
    
    public void setTitle(String title) {
        lbl_title.setText(title);
    }
    
    public void setAvailableModelsLabel(String text) {
        lbl_availableModels.setText(text);
    }
    
    public void setChosenModelsLabel(String text) {
        lbl_chosenModels.setText(text);
    }
    
    public void setAvailableModels(Vector<Model> models){
        availableModels = models;
        listbox_availableModels.setListData(models);
    }
    
    public void setChosenModels(Vector<Model> models){
        chosenModels = models;
        listbox_chosenModels.setListData(models);
    }
    
    
    public void addAddModelButtonActionListener(ActionListener listener) {
        btn_addSelectedModel.addActionListener(listener);
    }
    
    public void addRemoveModelButtonActionListener(ActionListener listener) {
        btn_removeSelectedModel.addActionListener(listener);
    }
    
    public void addClearSelectionButtonActionListener(ActionListener listener){
        btn_clearChosenModels.addActionListener(listener);
    }
    
    public void addSaveChosenModelsButtonActionListener(ActionListener listener){
        btn_saveChosenModels.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listbox_chosenModels = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listbox_availableModels = new javax.swing.JList();
        btn_addSelectedModel = new javax.swing.JButton();
        btn_removeSelectedModel = new javax.swing.JButton();
        lbl_chosenModels = new javax.swing.JLabel();
        lbl_availableModels = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        btn_clearChosenModels = new javax.swing.JButton();
        btn_saveChosenModels = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listbox_chosenModels.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listbox_chosenModels);

        listbox_availableModels.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listbox_availableModels);

        btn_addSelectedModel.setText("<-");

        btn_removeSelectedModel.setText("->");

        lbl_chosenModels.setText("Selected");

        lbl_availableModels.setText("Available");

        lbl_title.setText("Edit [model]");

        btn_clearChosenModels.setText("Clear");

        btn_saveChosenModels.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_saveChosenModels)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_clearChosenModels)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_addSelectedModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_removeSelectedModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_chosenModels)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_availableModels))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_chosenModels)
                    .addComponent(lbl_availableModels))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_addSelectedModel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_removeSelectedModel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_clearChosenModels)
                    .addComponent(btn_saveChosenModels))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addSelectedModel;
    private javax.swing.JButton btn_clearChosenModels;
    private javax.swing.JButton btn_removeSelectedModel;
    private javax.swing.JButton btn_saveChosenModels;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_availableModels;
    private javax.swing.JLabel lbl_chosenModels;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JList listbox_availableModels;
    private javax.swing.JList listbox_chosenModels;
    // End of variables declaration//GEN-END:variables
}
