package Views;

import java.awt.event.ActionListener;
import javax.swing.event.ListSelectionListener;

public class ProjectOverviewView extends javax.swing.JFrame {

    public ProjectOverviewView() {
        initComponents();
    }
    
    public void setInfoLabel(String text) {
        this.infoLabel.setText(text);
    }
    
    public void setOptionLabel(String text) {
        this.optionLabel.setText(text);
    }
    
    public void setTasks(Object[] tasks) {
        this.tasksList.setListData(tasks);
    }
    
    public void setViewButtonEnabled(boolean enable) {
        this.viewButton.setEnabled(enable);
    }
    
    public void addOptionComboActionListener(ActionListener listener) {
        this.optionCombo.addActionListener(listener);
    }
    
    public void addTasksListSelectionListener(ListSelectionListener listener) {
        this.tasksList.getSelectionModel().addListSelectionListener(listener);
    }
    
    public void addViewButtonActionListener(ActionListener listener) {
        this.viewButton.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        optionCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        optionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tasksList = new javax.swing.JList();
        viewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Project Overview");

        infoLabel.setText("project.toString()");

        jLabel2.setText("View:");

        optionLabel.setText("Tasks 'In Progress' for this Project");

        jScrollPane1.setViewportView(tasksList);

        viewButton.setText("View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(infoLabel)
                            .addComponent(optionLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox optionCombo;
    private javax.swing.JLabel optionLabel;
    private javax.swing.JList tasksList;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
