package Views;

import Models.SetOfUsers;
import javax.swing.DefaultComboBoxModel;

public class TaskDetailView extends javax.swing.JPanel {

    public TaskDetailView() {
        initComponents();
    }
    
    public void setIdLabelText(String text) {
        this.lblTaskID.setText(text);
    }
    
    public void setProjectTitleText(String text) {
        this.textTaskTitle.setText(text);
    }
    
    public void setStatus(DefaultComboBoxModel statusModel, int status) {
        this.cmboStatus.setModel(statusModel);
        this.cmboStatus.setSelectedIndex(status);
    }
    
    public void setPriority(DefaultComboBoxModel priorityModel, int priority) {
        this.cmboPriority.setModel(priorityModel);
        this.cmboPriority.setSelectedIndex(priority);
    }
    
    public void setAssignedTo(SetOfUsers users) {
        this.listAssignedTo.setListData(users);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditReport = new javax.swing.JButton();
        lblReport = new javax.swing.JLabel();
        cmboReport = new javax.swing.JComboBox();
        btnSaveTask = new javax.swing.JButton();
        cmboStatus = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAssignedTo = new javax.swing.JList();
        lblTaskID = new javax.swing.JLabel();
        lblTaskDetails = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        cmboPriority = new javax.swing.JComboBox();
        lblPriority = new javax.swing.JLabel();
        textTaskTitle = new javax.swing.JTextField();
        lblTaskTitle = new javax.swing.JLabel();
        btnEditAssignedTo = new javax.swing.JButton();
        lblAssignedTo = new javax.swing.JLabel();

        btnEditReport.setText("Edit Selected Report");

        lblReport.setText("Report:");

        cmboReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSaveTask.setText("Save Task Details");

        cmboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        listAssignedTo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listAssignedTo);

        lblTaskID.setText("ID:");

        lblTaskDetails.setText("Task Details");

        lblStatus.setText("Status:");

        cmboPriority.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPriority.setText("Priority:");

        lblTaskTitle.setText("Title:");

        btnEditAssignedTo.setText("Add / Remove User");

        lblAssignedTo.setText("Assigned to:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAssignedTo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTaskDetails)
                                .addGap(331, 331, 331)
                                .addComponent(lblTaskID))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblTaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblStatus)
                                            .addGap(26, 26, 26)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPriority)
                                            .addComponent(lblReport))
                                        .addGap(23, 23, 23)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmboReport, 0, 199, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditReport))
                                    .addComponent(cmboPriority, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textTaskTitle, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditAssignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaskDetails)
                    .addComponent(lblTaskID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaskTitle)
                    .addComponent(textTaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriority)
                    .addComponent(cmboPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmboReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReport)
                    .addComponent(btnEditReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAssignedTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditAssignedTo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveTask)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditAssignedTo;
    private javax.swing.JButton btnEditReport;
    private javax.swing.JButton btnSaveTask;
    private javax.swing.JComboBox cmboPriority;
    private javax.swing.JComboBox cmboReport;
    private javax.swing.JComboBox cmboStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssignedTo;
    private javax.swing.JLabel lblPriority;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTaskDetails;
    private javax.swing.JLabel lblTaskID;
    private javax.swing.JLabel lblTaskTitle;
    private javax.swing.JList listAssignedTo;
    private javax.swing.JTextField textTaskTitle;
    // End of variables declaration//GEN-END:variables
}
